---
apiVersion: external-postgres.wafflehacks.cloud/v1
kind: Database
metadata:
  name: constant
spec:
  # Define the database user's password inline
  password:
    value: testing
  retainOnDelete: false
  secret:
    name: constant-database-secret
    namespaces:
      - default
