---
apiVersion: v1
kind: Secret
metadata:
  name: testing-database-password
stringData:
  password: this-is-a-test
---
apiVersion: external-postgres.wafflehacks.cloud/v1
kind: Database
metadata:
  name: secret
spec:
  # Pull the database user's password from a secret
  password:
    fromSecret:
      name: testing-database-password
      key: password
      namespace: default
  retainOnDelete: false
  secret:
    namespaces:
      - default
