---
name: Lint

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  manifests:
    name: Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install yamllint
      - run: yamllint -s -f github .

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt --all --check

  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_VERSION: v0.3.3
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: /home/runner/.cache/sccache
      # SCCACHE_RECACHE: 1 # Uncomment this to clear cache, then comment it back out
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - name: Install sccache
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          curl -L "$BASE_URL/$SCCACHE_VERSION/$FILE.tar.gz" | tar xz
          mv -f $FILE/sccache $HOME/.local/bin/sccache
        env:
          BASE_URL: https://github.com/mozilla/sccache/releases/download
          FILE: sccache-${{ env.SCCACHE_VERSION }}-x86_64-unknown-linux-musl

      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache sccache
        uses: actions/cache@v3
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sccache-

      - name: Start sccache
        run: sccache --start-server

      - run: cargo check
      - run: cargo build --release

      - name: Show sccache stats
        run: sccache --show-stats
      - name: Stop sccache
        run: sccache --stop-server || true
